### PR TITLE
Bandwith limiter

### PR DESCRIPTION
**Pull request by maghuro**
first and very simple implementation
missing IP address of that interface

source: https://gist.github.com/rbrooks/2719817

### CODE REVIEW

**Comment by maghuro** [comment]
Maybe it's not the right way, but maybe it can give you hints and ideas :)

**Comment by jackyaz** [comment]
I'm curious, do we know if tc only affect WAN -> LAN and LAN -> WAN or if LAN -> LAN could be affected too?

**Comment by maghuro** [comment]
Great question.
But logically, it'll affect that interface, so all 3 may be affected...

So if i send some file from Guest1 to Guest2, and Guest1 has a 100Mbit download/upload limit and Guest2 has a 30Mbit download limit, probably Guest2 will receive the file and 30Mbit second..

**Comment by jackyaz** [comment]
Are you able to test if that is the case? I don't have any proper clients to test with on a wireless guest (all i have is IoT stuff!)

**Comment by jackyaz** [comment]
Not a problem if it does, so long as we can advertise what will happen when a network is bandwidth limited

**Comment by jackyaz** [comment]
looking at https://gist.github.com/rbrooks/2719817 we might be able to specify ip dst matches, so that only non private ips are matched?

**Comment by maghuro** [comment]
> Are you able to test if that is the case? I don't have any proper clients to test with on a wireless guest (all i have is IoT stuff!)

not at home right now and for the next days :(

**Comment by maghuro** [comment]
> looking at https://gist.github.com/rbrooks/2719817 we might be able to specify ip dst matches, so that only non private ips are matched?

I didn't understand properly that.
But afaik, as long as we define the subnet (xx.xx.xx.xx/24) all IPs from that IF are included. And we only want to "mess" with that specifically interface.

So, as long as we cap down/up from, let's say, wl0.1 to router, we're all good.

**Comment by jackyaz** [comment]
I think we can simplify this. It may be best to just use the nvram variables (if they exist) that the user enters in Asus' existing UI. We just need to update YazFi to do the TC stuff

**Comment by maghuro** [comment]
And then we will rely on bandwithd limited instead of adaptive QoS?
I think it is better to have independent bandwithd settings for each guest wifi.... In this case, 6 different possibilities

**Comment by jackyaz** [comment]
I'm not sure our TC rules would work if the router is set to Adaptive QoS, nor what would happen is QoS is not enabled? The Asus option for guests shows:

image

**Comment by maghuro** [comment]
Hum....
But as soon as you activate bandwithd limiter mode on guest wifi, adaptive QoS will be disabled...

**Comment by jackyaz** [comment]
That's what I mean, if we leave the system in adaptive QoS, will manually adding tc rules for bandwidth limitation actually apply? i'd hope so given we use different interface to br0, but we'd need to test this

**Comment by maghuro** [comment]
Let's test it with adaptive QoS on! I'm able to do it.
IMHO it will work because, as you said, we use different interfaces for each guest Network

**Comment by jackyaz** [comment]
I'll revisit this in future - my proposed move to additional bridge interfaces may complicate things

**Pull request closed without merging**
