### PR TITLE
4.4.3

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Jack Yaz,

This pull request is for all the latest changes I've made to the shell script (**YazFi.sh**) and the JavaScript code (**YazFi_www.js**) to support the new "**DHCP Lease Time**" configuration option.

For background & context for this new feature here is the SNBF thread where it was discussed recently:
https://www.snbforums.com/threads/yazfi-dhcp-lease-times.82005/

I don't know what your protocol is for submitting code changes so if there's anything else I need to do let me know. BTW, I tried to stay close to your coding style but I may have strayed from it at times, so I apologize in advance if this causes more work for you if you want to change the style for consistency.

Thanks.

### CODE REVIEW

**Review by Martinski4GitHub — COMMENTED** [review]
Just a minor change for indentation alignment.

**Comment by Martinski4GitHub** [comment]
I've made latest changes to fix 3 GUI bugs (trivial & really cosmetic) found with "DHCP Start" & "DHCP End" valid range validation. Nothing critical at all.

**Comment by jackyaz** [comment]
Looks good! Since I have no way of testing, we could start by pushing to the develop branch and people can dynamically change to it by running ```YazDHCP develop```

**Comment by Martinski4GitHub** [comment]
> Looks good! Since I have no way of testing, we could start by pushing to the develop branch and people can dynamically change to it by running `YazDHCP develop`

Yeah, that sounds good. Caution is a good thing.
Thanks.

**Comment by jackyaz** [comment]
> > ... we could start by pushing to the develop branch and people can dynamically change to it by running `YazDHCP develop`
> 
> BTW, is there anything else I need to do specifically for the "YazFi develop" branch?

You need to set the branch variable at the top of the script to develop, instead of master.

Also you need to minify the JS and include in the ASP (or I can do this after merging)

**Comment by Martinski4GitHub** [comment]
Based on this message on Codacy: "**It seems like the branch develop is not being analyzed.**" it looks like it's not an actual problem with the static code analysis.

**Comment by jackyaz** [comment]
Enabled codacy for develop and triggered a re-run of the check. Did you see my comments throughout the code?

**Comment by jackyaz** [comment]
Can you check my comments in the review further up please? 

image

happy to merge into develop once clarified

**Comment by Martinski4GitHub** [comment]
> Can you check my comments in the review further up please?
> 
Perhaps I'm looking at the wrong places, but I'm not seeing any of your PR reviews when I browse through the PR "**Conversation**", "**Commits**", or "**Files changed**" tabs. In any event, below are my responses.

WRT the code change in the DHCP validation function, it was made because the valid range for "**DHCP Start**" is 2 to **253** (inclusive), and the valid range for "**DHCP End**" is **3** to 254 (inclusive). Before the code change, both parameters had a check of "2 to 254" in the validation routine. This fix matches the corresponding changes made in the JavaScript DHCP validator as well.

For further context WRT this change, you can see this post in SNBF:
https://www.snbforums.com/threads/yazfi-dhcp-lease-times.82005/#post-806205

WRT the code change in the bottom screenshot, yes the "**DHCPLease_withGUISupport**" variable was put there for testing purposes when I initially made the changes in the shell script to support "DHCP Lease" but *without* the corresponding WebGUI support in the JavaScript file (which came much later). Now with the GUI support implemented, it's no longer really needed.

> happy to merge into develop once clarified
>
OK, let me know if there's anything else WRT this PR that I can help you with.

Thanks.

**Comment by Martinski4GitHub** [comment]
> 
> WRT the code change in the bottom screenshot, yes the "**DHCPLease_withGUISupport**" variable was put there for testing purposes when I initially made the changes in the shell script to support "DHCP Lease" but _without_ the corresponding WebGUI support in the JavaScript file (which came much later). Now with the GUI support implemented, it's no longer really needed.
> 
FYI, I've removed the code related to the "**DHCPLease_withGUISupport**" variable which was no longer necessary.

**Pull request merged**
