### PR TITLE
Only "5GHZ" if router doesn't have two 5Ghz

### PR DESCRIPTION
**Pull request by maghuro**
not tested
please check if "nvram get wl2_vifnames" = blank is the correct way to check if router has the second 5Ghz band.

### CODE REVIEW

**Comment by maghuro** [comment]
@jackyaz have you missed it? :)

**Comment by jackyaz** [comment]
Sorry, I've been busy with other projects, and this seems to be a cosmetic issue. I'll get to it soon

**Comment by maghuro** [comment]
Take your time master, just cosmetics :)

**Comment by jackyaz** [comment]
It looks like this could cause unintended duplicate VPN policy routing rules for upgrading users. Have you tested what happens when the network is called 5GHz instead of GHz1 in policy routing?

**Comment by maghuro** [comment]
No, just commited the code.
In fact, it can cause duplicates. Before apllying any Policy Routing rules, why don't we search for them and remove all?

If it is bjork to implement, please forget it. We're dealing only with aesthetics here :)

**Comment by jackyaz** [comment]
Closing this in favour of reviewing the bandwidth limiter work

**Comment by maghuro** [comment]
Thanks pal!!

**Pull request closed without merging**
